on:
  push:
  pull_request:

name: build
jobs:
  build-scene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: install decentraland
        run: npm install -g decentraland

      - name: dcl build
        run: dcl build

      - name: dcl export
        run: dcl export

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: scene-${{ github.sha }}
          path: |
            *.zip
